name: build-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    paths:
      - .github/workflows/build-ci.yml
      - contrib/src/luajit/luajit-v2.1.0-beta3.patch
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      no_dll:
         # actions run ID
         description: 'Do not build windows lib as dll'
         # Default value if no value is explicitly provided
         default: ''
         # Input has to be provided for the workflow to run
         required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ios:
    # The type of runner that the job will run on
    runs-on: macos-12
    
    strategy:
      matrix:
        arch:
          - arm64
          - x64
    
    env:
      BUILD_TARGET: ios
      BUILD_ARCH: ${{ matrix.arch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '13.4'

      - name: Install brew
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: install env
        run: brew install automake

      - name: Build
        run: cd build && ./build.sh -p=ios --libs=all --mode=release
